package com.alexeiddg.telegram.bot.session;

public enum UserState {
    NONE,
    // Signup state
    SIGNUP,
    SIGNUP_NAME,
    SIGNUP_USERNAME,
    SIGNUP_ROLE,
    SIGNUP_MANAGER,
    SIGNUP_FINISH,
    // Login state
    LOGIN_USERNAME,
    // Main menu state
    MAIN_MENU,
    MAIN_MENU_BEGIN,
    MAIN_MENU_PROJECTS,
    MAIN_MENU_SPRINT,
    MAIN_MENU_TEAM,
    MAIN_MENU_CREATE_TASK,
    MAIN_MENU_VIEW_TASKS,
    // Project state
    PROJECT,
    // Project create state
    PROJECT_CREATE,
    PROJECT_CREATE_NAME,
    PROJECT_CREATE_DESCRIPTION,
    PROJECT_CREATE_MANAGER,
    PROJECT_CREATE_TEAM_DECISION,
    PROJECT_CREATE_TEAM_SELECT,
    PROJECT_CREATE_CONFIRMATION,
    // Project update state
    PROJECT_UPDATE,
    // Project delete state
    PROJECT_DELETE,
    PROJECT_DELETE_CONFIRM,
    // Sprint state
    SPRINT,
    // Sprint creation flow
    SPRINT_CREATE_PROJECT_SELECT,
    SPRINT_CREATE_NAME,
    SPRINT_CREATE_START_DATE,
    SPRINT_CREATE_END_DATE,
    SPRINT_CREATE_CONFIRMATION,
    // Task state
    TASK,
    // Task creation flow
    TASK_CREATE,
    TASK_CREATE_NAME,
    TASK_CREATE_DESCRIPTION,
    TASK_CREATE_ASSIGNEE,
    TASK_CREATE_SPRINT,
    TASK_CREATE_PRIORITY,
    TASK_CREATE_STATUS,
    TASK_CREATE_TYPE,
    TASK_CREATE_STORY_POINTS,
    TASK_CREATE_DUE_DATE,
    TASK_CREATE_CONFIRMATION,
    // Task update flow
    TASK_UPDATE,
    TASK_UPDATE_SELECT,
    TASK_UPDATE_FIELD,
    TASK_UPDATE_NAME,
    TASK_UPDATE_DESCRIPTION,
    TASK_UPDATE_PRIORITY,
    TASK_UPDATE_STATUS,
    TASK_UPDATE_TYPE,
    TASK_UPDATE_STORY_POINTS,
    TASK_UPDATE_DUE_DATE,
    TASK_UPDATE_BLOCKED,
    // Task delete flow
    TASK_DELETE,
    TASK_DELETE_CONFIRM,
}
