package com.alexeiddg.telegram.bot.session;

public enum UserState {
    NONE,
    SIGNUP,
    SIGNUP_NAME,
    SIGNUP_USERNAME,
    SIGNUP_ROLE,
    SIGNUP_MANAGER,
    SIGNUP_FINISH,
    LOGIN_USERNAME,
    MAIN_MENU,
    MAIN_MENU_BEGIN,
    MAIN_MENU_PROJECTS,
    MAIN_MENU_SPRINT,
    MAIN_MENU_TEAM,
    MAIN_MENU_CREATE_TASK,
    MAIN_MENU_VIEW_TASKS,
    PROJECT,
    PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_DELETE,
}
