package com.alexeiddg.telegram.bot.session;

public enum UserState {
    // 🚫 Generic / No State
    NONE,

    // 🔐 Signup Flow
    SIGNUP, // TODO: Check if possible to remove this state
    SIGNUP_NAME,
    SIGNUP_USERNAME,
    SIGNUP_ROLE,
    SIGNUP_MANAGER,
    SIGNUP_FINISH,

    // 🔐 Login Flow
    LOGIN_USERNAME,
    LOGIN_PASSWORD,

    // 🧭 Main Menu
    MAIN_MENU,
    MAIN_MENU_BEGIN, // TODO: Check if possible to remove this state
    MAIN_MENU_VIEW_TASKS,
    MAIN_MENU_CREATE_TASK,
    MAIN_MENU_SPRINT,
    MAIN_MENU_PROJECTS,
    MAIN_MENU_TEAM,
    MAIN_MENU_REPORTS,

    // Project state
    PROJECT,
    // Project create state
    PROJECT_CREATE,
    PROJECT_CREATE_NAME,
    PROJECT_CREATE_DESCRIPTION,
    PROJECT_CREATE_MANAGER,
    PROJECT_CREATE_TEAM_DECISION,
    PROJECT_CREATE_TEAM_SELECT,
    PROJECT_CREATE_CONFIRMATION,
    // Project update state
    PROJECT_UPDATE,
    // Project delete state
    PROJECT_DELETE,
    PROJECT_DELETE_CONFIRM,
    // Sprint state
    SPRINT,
    // Sprint creation flow
    SPRINT_CREATE_PROJECT_SELECT,
    SPRINT_CREATE_NAME,
    SPRINT_CREATE_START_DATE,
    SPRINT_CREATE_END_DATE,
    SPRINT_CREATE_CONFIRMATION,

    // ✅ Task General
    TASK,
    TASK_SELECT_START,
    TASK_SELECT_COMPLETE,
    TASK_LOG_HOURS,
    TASK_SELECT_REOPEN,
    TASK_DETAILS,

    // Task creation flow
    TASK_CREATE,
    TASK_CREATE_NAME,
    TASK_CREATE_DESCRIPTION,
    TASK_CREATE_ASSIGNEE,
    TASK_CREATE_SPRINT,
    TASK_CREATE_PRIORITY,
    TASK_CREATE_STATUS,
    TASK_CREATE_TYPE,
    TASK_CREATE_STORY_POINTS,
    TASK_CREATE_DUE_DATE,
    TASK_CREATE_CONFIRMATION,

    // Task update flow
    TASK_UPDATE_SELECT,
    TASK_UPDATE_NAME,
    TASK_UPDATE_DESCRIPTION,
    TASK_UPDATE_PRIORITY,
    TASK_UPDATE_STATUS,
    TASK_UPDATE_TYPE,
    TASK_UPDATE_STORY_POINTS,
    TASK_UPDATE_DUE_DATE,
    TASK_UPDATE_BLOCKED,
    TASK_UPDATE_ASSIGNEE,
    TASK_UPDATE_LOG_HOURS,

    // Task delete flow
    TASK_DELETE,
    TASK_DELETE_CONFIRM, TASK_UPDATE,


    // Reports
    REPORTS_MENU,
}
