apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:oracle:thin:@MTDRDB_tp?TNS_ADMIN=/mtdrworkshop/creds
  SPRING_DATASOURCE_USERNAME: APPUSER
  SPRING_DATASOURCE_PASSWORD: Welcome12345
  TELEGRAM_BOT_TOKEN: 7855236737:AAFguH95PLCxP33XHkuiLMkSwaDual8HFV0
  TELEGRAM_BOT_USERNAME: oci_manager_bot
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-service
  labels:
    app: telegram-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: telegram-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-deployment
  labels:
    app: telegram-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telegram-app
  template:
    metadata:
      labels:
        app: telegram-app
    spec:
      volumes:
        - name: oracle-wallet
          secret:
            secretName: oracle-wallet
      containers:
        - name: telegram
          # Add volume mount for Oracle wallet
          volumeMounts:
            - name: oracle-wallet
              mountPath: /mtdrworkshop/creds
              readOnly: true
          image: mx-queretaro-1.ocir.io/ax83el69bkfn/mtdr-ocir-telegram:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: telegram-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5