apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.mx-queretaro-1.oraclecloud.com))(connect_data=(service_name=g081b0f6287a97d_mtdrdb_tp.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
  SPRING_DATASOURCE_USERNAME: ADMIN
  SPRING_DATASOURCE_PASSWORD: Welcome12345!
  TELEGRAM_BOT_TOKEN: 7855236737:AAFguH95PLCxP33XHkuiLMkSwaDual8HFV0
  TELEGRAM_BOT_USERNAME: oci_manager_bot
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-service
  labels:
    app: telegram-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: telegram-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-deployment
  labels:
    app: telegram-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telegram-app
  template:
    metadata:
      labels:
        app: telegram-app
    spec:
      containers:
        - name: telegram
          image: mx-queretaro-1.ocir.io/ax83el69bkfn/mtdr-ocir-telegram:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: telegram-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5