apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:oracle:thin:@MTDRDB_tp?TNS_ADMIN=/mtdrworkshop/creds
  SPRING_DATASOURCE_USERNAME: APPUSER
  SPRING_DATASOURCE_PASSWORD: Welcome12345
  TELEGRAM_BOT_TOKEN: 7855236737:AAFguH95PLCxP33XHkuiLMkSwaDual8HFV0
  TELEGRAM_BOT_USERNAME: oci_manager_bot