name: Local CI Pipeline (Docker Build & Push)

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, web, telegram]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Node.js (for frontend)
        if: matrix.service == 'frontend'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK (for Java services)
        if: matrix.service == 'web' || matrix.service == 'telegram'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Root Maven Build (required for all Java services)
        if: matrix.service == 'web' || matrix.service == 'telegram'
        run: mvn clean install -DskipTests
        working-directory: ${{ github.workspace }}

      - name: Install frontend dependencies
        if: matrix.service == 'frontend'
        run: npm install --legacy-peer-deps
        working-directory: ${{ github.workspace }}/frontend

      - name: Docker Build & Push to Docker Hub (Retries 3 Times)
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: alexeiddg5/mtdr-${{ matrix.service }}:latest
          platforms: linux/amd64,linux/arm64