name: Full CI Pipeline (no docker push)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm run test

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Build frontend (Next.js)
        run: npm run build

      - name: Build frontend Docker image
        run: docker build --platform=linux/amd64 -f Dockerfile -t mx-queretaro-1.ocir.io/ax83el69bkfn/mtdr-ocir-front:latest .


  telegram:
    name: Telegram Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telegram

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Telegram backend
        run: ../mvnw clean install

      - name: Build Telegram Docker image
        run: docker build --platform=linux/amd64 -f Dockerfile -t mx-queretaro-1.ocir.io/ax83el69bkfn/mtdr-ocir-telegram:latest .

  web:
    name: Web Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Web backend
        run: ../mvnw clean install

      - name: Build Web Docker image
        run: docker build --platform=linux/amd64 -f Dockerfile -t mx-queretaro-1.ocir.io/ax83el69bkfn/mtdr-ocir-web:latest .
