apiVersion: v1
kind: Secret
metadata:
  name: web-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:oracle:thin:@MTDRDB_tp?TNS_ADMIN=/mtdrworkshop/creds
  SPRING_DATASOURCE_USERNAME: APPUSER
  SPRING_DATASOURCE_PASSWORD: Welcome12345
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      volumes:
        - name: oracle-wallet
          secret:
            secretName: oracle-wallet
      containers:
        - name: web
          # Add volume mount for Oracle wallet
          volumeMounts:
            - name: oracle-wallet
              mountPath: /mtdrworkshop/creds
              readOnly: true
          image: mx-queretaro-1.ocir.io/ax83el69bkfn/mtdr-ocir-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: web-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5