apiVersion: v1
kind: Secret
metadata:
  name: web-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:oracle:thin:@MTDRDB_tp?TNS_ADMIN=/mtdrworkshop/creds
  SPRING_DATASOURCE_USERNAME: APPUSER
  SPRING_DATASOURCE_PASSWORD: Welcome12345